kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-dynamic-plugins-root" .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
